app:
  id: testdb
  format: DESIGNER
  base-path: "D:\\1С-Framework\\src\\bsl"

  source-set:
    - path: "."
      name: testdb
      type: "CONFIGURATION"
      purpose: [ "MAIN" ]
    - path: "exts/YAXUNIT"
      name: YAXUNIT
      type: "EXTENSION"
      purpose: [ "TESTING" ]
    - path: "exts/Smoke"
      name: Smoke
      type: "EXTENSION"
      purpose: [ "TESTING" ]

  connection:
    connection-string: 'Srvr="KOMPUTER";Ref="TestDB";'
    user: "a.terletskiy@sodru.com"
    password: "Alex80Alex"

  platform-version: "8.3.27.1859"

  tools:
    builder: DESIGNER
    enterprise:
      additional-launch-keys:
        - "/TESTMANAGER"
