@echo off
rem GKSTCPLK-2468: enable server-side debug on 1C:Enterprise 8.3 Server Agent
rem Adds -debug flag to ragent.exe via service binPath update.
rem Auto-generated by Claude. Run from elevated context.

echo === Stopping 1C Server Agent service ===
sc.exe stop "1C:Enterprise 8.3 Server Agent"
if %ERRORLEVEL% NEQ 0 (
    echo WARNING: stop returned %ERRORLEVEL% — service may have been stopped already
)

rem Wait for clean shutdown
timeout /t 3 /nobreak >nul

echo.
echo === Updating binPath to include -debug ===
sc.exe config "1C:Enterprise 8.3 Server Agent" binPath= "\"C:\Program Files (x86)\1cv8\8.3.27.1936\bin\ragent.exe\" -srvc -agent -regport 1541 -port 1540 -range 1560:1591 -debug -d \"C:\Program Files (x86)\1cv8\srvinfo\""
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: sc config failed with %ERRORLEVEL%
    pause
    exit /b 1
)

echo.
echo === Starting 1C Server Agent service ===
sc.exe start "1C:Enterprise 8.3 Server Agent"
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: sc start failed with %ERRORLEVEL%
    pause
    exit /b 1
)

echo.
echo === Verifying new binPath ===
sc.exe qc "1C:Enterprise 8.3 Server Agent"

echo.
echo === DONE ===
echo Server-side debug enabled. -debug flag added to ragent.exe.
echo You can close this window now.
timeout /t 5 /nobreak >nul
